parameters:
#    block_ip_people.example.class: BlockIP\PeopleBundle\Example

services:
#    block_ip_people.example:
#        class: %block_ip_people.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
